### ISSUE TITLE
Add Billing info

### ISSUE THREAD

**Issue by mrplum** [mrplum/plum_cart#12]
In a first stage we are going to engage MercadoPago integration

https://www.mercadopago.com.ar/developers/es/guides/online-payments/checkout-pro/integration

**Comment by luuchorocha** [comment]
I have tested it and the checkout works as expected. There are some minor improvements pending, but the main feature is working. Toghether with this feature, the shipping form should be connected to this new flow. I have reviewed and merged PR #11
