### ISSUE TITLE
Improve sidebar toggle button

### ISSUE THREAD

**Issue by mrplum** [mrplum/plum_cart#7]
Currently to open the sidebar we need to click in the top left dots. We should add something more explicit (maybe bigger) to open the Sidebar

![Screen Shot 2020-11-05 at 12 21 06](https://user-images.githubusercontent.com/6596218/98259861-62836880-1f61-11eb-92fe-af315eab9ff3.png)

![Screen Shot 2020-11-05 at 12 20 50](https://user-images.githubusercontent.com/6596218/98259828-58616a00-1f61-11eb-8d68-18a4ab205719.png)

Something like sounds like a good start for me
![Screen Shot 2020-11-05 at 12 22 26](https://user-images.githubusercontent.com/6596218/98260017-93fc3400-1f61-11eb-8357-fc3fe5efc594.png)

**Comment by luuchorocha** [comment]
It has been fixed but the changes are in the `mercadopago` branch.
The button is a float button that looks the following (Look at the bottom right corner): 

![plumcart1](https://user-images.githubusercontent.com/7143275/100859396-f287d580-346d-11eb-902f-2455bb4cfbbc.png)
